//@version=6
indicator("PlayBit EMA", "PB-EMA", overlay=true)

length = input.int(200, "Length")
lineColor = input.color(#000000, "Line-Color")
emaTop = ta.ema(input.source(high, "Top-Source"), length)
emaBot = ta.ema(input.source(close, "Bot-Source"), length)
fillColor =  close < emaBot ? input.color(color.rgb(255, 0, 0, 67), "Fill-Color-Below") : 
             close > emaTop ? input.color(color.rgb(27, 255, 27, 67), "Fill-Color-Above") : 
                              input.color(color.rgb(120, 123, 134, 67), "Fill-Color-Neutral")
pTop = plot(emaTop, color=lineColor)
pBot = plot(emaBot, color=lineColor)
fill(pTop, pBot, color=fillColor, fillgaps=true)

  
